#!/bin/bash
# Declaring a few misc variables
vspiversion=2.0 # SPI version
vspibuild=2017 # SPI build number
vbranch=Stable # SPI build branch
vsysarch=$(getconf LONG_BIT) # System architecture

firew1 ()	{
	# Opening default Squid port 3128 for clients to connect
	iptables -I INPUT -p tcp --dport 3128 -j ACCEPT
	# Saving firewall rules
	service iptables save
}

firew2 ()	{
	# Opening default Squid port 3128 for clients to connect
	iptables -I INPUT -p tcp --dport 3128 -j ACCEPT
	# Saving firewall rules
	iptables-save
}

# Function for Ubuntu
ubt ()	{
	# Updating package database
	apt-get update
	# Installing necessary packages (Squid, apache2-utils for htpassword and dependencies)
	apt-get install apache2-utils squid3 -y
	# Asking user to set a username via read and writing it into $usrn
	read -e -p "Your desired username: " usrn
	# Creating user with username from $usrn and asking user to set a password
	htpasswd -c /etc/squid3/passwd $usrn
	# Downloading Squid configuration
	wget -O /etc/squid3/squid.conf https://raw.githubusercontent.com/UJtriumphs/Squid-Proxy-Installer/master/spi-ubuntu.conf --no-check-certificate
	# Copying squid3.conf from init to init.d for startup script
	cp /etc/init/squid3.conf /etc/init.d/squid3
	# Creating empty blacklist.acl file for further blacklisting entries
	touch /etc/squid3/blacklist.acl	
	# Restarting Squid and enabling its service
	service squid3 restart && update-rc.d squid3 defaults
	# Running function firew2
	firew2
}

# Default function with information
dinfo ()	{
	echo "Squid Proxy Installer $vspiversion Build $vspibuild"
	echo "You are using builds from the $vbranch branch"
	echo "-ubuntu  -- Ubuntu"
	echo ""
}

# Checking $1 and running corresponding function
case $1 in
	'-ubuntu') # If option "-ubuntu" run function ubt
		ubt;; # Ubuntu
	*) # If option empty or non existing run function info
		dinfo;; # Default, information about available options and et cetera
esac
